name: Deploy test environment
 
on: 
  push:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - name: Checkout code
      uses: actions/checkout@main

      # Log into Azure
    - name: Login into Azure
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PWD }}

      # Deploy ARM template
    - name: Deploy ARM template
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: az deployment group create --resource-group ${{ secrets.AZURE_TEST_ENV }} --template-file https://github.com/francesco-paglia/IaC/blob/5095b046791e05d702066b6c25f65d7b3f606291/test-env-template.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
