name: Deploy test environment
 
on: 
  push:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PWD }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: test-env
        template: ./test-env-template.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
