name: Deploy test environment

on: 
  push:
    branches:
    - main
    paths:
    - 'templates/test-env-template.json'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - name: Checkout code
      uses: actions/checkout@main
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      # Log into Azure
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Deploy ARM template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_TEST_ENV }}
        template: ./test-env-template.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
